### ISSUE TITLE
Last dev build returns status not found

### ISSUE THREAD

**Issue by mmuziek** [WooMinecraft/woominecraft-wp#10]
hi there.
i was trying out the latest dev build and tested it against the plugin i have
and i get
[21:50:55] [Server thread/INFO]: mmuziek issued server command: /woo check
[21:50:56] [Server thread/WARN]: [WooMinecraft] JSONObject["status"] not found.
its possible i have my plugin behind on commits but when i check it myself:
i get
{"success":false,"data":{"msg":"No results for the following players: \"mmuziek\"","status":"empty","code":6}}
the strange thing is that i do have commands waiting and i do have the name mmuziek but still it doesnt see it i think it has something to do with the \ inside the strings

**Comment by TekkitCommando** [comment]
This may be the Bukkit plugin so could you please also post this issue on the Bukkit Plugin repo, thank you! :)
