### ISSUE TITLE
[Question] Adding the player ID field to "My Account"

### ISSUE THREAD

**Issue by Baktus79** [WooMinecraft/woominecraft-wp#106]
Does anyone here know how I can add the player ID field to "My account", so that it is filled in automatically at checkout?

**Comment by JayWood** [comment]
https://www.cssigniter.com/how-to-add-a-custom-user-field-in-wordpress/

Look into that - you'll also need to hook into the checkout screen to pull in the value.

**Comment by Baktus79** [comment]
Thank you very much for your response, here was a lot of good information to work with :)
