### ISSUE TITLE
variable commands

### ISSUE THREAD

**Issue by mmuziek** [WooMinecraft/woominecraft-wp#12]
hi there

i was trying to add variable products but i can only set the first variable command
so if there are 4 options like
1 year
6 months
3 months 
1 month

it only allows me to add a command to 1 year not the rest :(

**Comment by TekkitCommando** [comment]
Wouldn't this be a thing with WooCommerce and not WooMinecraft? Hmm @JayWood I leave this to you :P

**Comment by mmuziek** [comment]
it worked before . but it aint working now in this last release so there was a change that makes the problem

**Comment by TekkitCommando** [comment]
Ah well in any case the WordPress side is for Jay I don't even start my PHP classes till after my Java and Python ones are done haha

**Comment by JayWood** [comment]
@mmuziek I see it, thanks for testing that out.  I'll hopefully get that fixed and the resend donations done today, then we should be good.

**Comment by JayWood** [comment]
@mmuziek I think at this point you're our official QA guy :+1: :smile_cat:
