### ISSUE TITLE
Check out page not asking for player ign

### ISSUE THREAD

**Issue by littlemarc2011** [WooMinecraft/woominecraft-wp#14]
Well after installing everything... WooMinecraft and WooCommerce I added a product and set a command. When I got to check out it never asks for the player id and asks for shipping details. How do I disable shipping details and have it ask for player ign? Basicly like how it is in: https://youtu.be/vHrxSzo7JnQ?t=4m36s

Are some of my settings wrong? I setup everything like the wiki said.

**Comment by JayWood** [comment]
Questions for you - 

* What kind of product was it, variable or general?
* Did you verify the command was actually saved? If setting variable product commands you must click save.
* The product should be 'virtual' no shipping needed!? in fact I disable shipping in my WooCommerce admin.

You should see this field above billing details: 
![](https://i.gyazo.com/b876d6b0847ba0868bb871cbbf075d5c.png)

**Comment by littlemarc2011** [comment]
I followed your exact tutorial and even checked virtual. This was done under a simple product, and for some reason it still asks for shipping details even with virtual checked.

**Comment by JayWood** [comment]
@littlemarc2011 you shouldn't even have to disable shipping for that to show up.  Do you not get a billing screen at all? Is it just shipping?

**Comment by JayWood** [comment]
@littlemarc2011 reason I ask is even if I enable shipping, I still have billing details available, have you tried this on a different theme?

![](https://i.gyazo.com/167e927572c3c7e663b386a5d337fbf4.png)

**Comment by littlemarc2011** [comment]
It shows this: http://i.imgur.com/QCacOe1.png

**Comment by JayWood** [comment]
What theme are you using? I'd like to get my hands on it, because themes can overwrite that form. And if the theme didn't put in the hook, well, that's the problem, but I can't tell without looking at the theme.

**Comment by littlemarc2011** [comment]
SparklingVersion: 2.2.1
By Colorlib

**Comment by littlemarc2011** [comment]
I checked with default theme and the same issue... This is a fresh, up to date install of everything... Maybe in wiki you can put the steps you took, maybe do a fresh install yourself and try it?

**Comment by JayWood** [comment]
@littlemarc2011 When I get home this evening I will do that, thanks for the info.

**Comment by littlemarc2011** [comment]
@JayWood Thank you.

**Comment by mmuziek** [comment]
Ok @JayWood 
i'm back from some time i updated woominecraft WP and the plugin to the latest edition. and now the player IGN is indeed not showing up on the order page while it was showing up before so something has changed?

**Comment by JayWood** [comment]
@mmuziek yes, product meta keys have changed, so the has-items check which determines rather or not to show the dialog is now not showing the dialog.  To fix, just go into your products and re-save your commands.  

Down-side, you may have to re-add your commands :cry: upside - this is a more modular thing to do and will allow flexibility in the future.

**Comment by HappyHarm** [comment]
Did you tick the virtual box when you edit the item? That should remove the shipment fields at least.

**Comment by mmuziek** [comment]
@JayWood well i cannot even add commands to items anymore the textboxes are gone :(

**Comment by mmuziek** [comment]
@jaywood even the Minecraft IGN thiny is now fixed i didnt have to redo all the commands
i think its something else but that error i talkt about before is a serious matter

**Comment by JayWood** [comment]
@mmuziek WHat 'error' you talked about before? This one: `woominecraft-wp-1.0.1/functions.php has been deactivated due to an error: Plugin file does not exist.`

That's probably due where the plugin was originally downloaded off of github. But, if you got the update from WordPress.org, the folder name will have changed, which is what caused the error.

**Comment by mmuziek** [comment]
@jaywood either way its fixed justletting you know
