### ISSUE TITLE
Commands with Quotes may not work

### ISSUE THREAD

**Issue by JayWood** [WooMinecraft/woominecraft-wp#16]
See here: https://wordpress.org/support/topic/tried-to-add-pex-command-but-it-doesnt-work?replies=4

Apparently commands with double quotes (") may not work, needs testing.

Example command: `pex user %s group add VIP "" 30`

**Comment by puccino** [comment]
Any update here ?

**Comment by JayWood** [comment]
This fix is now in, closing.
