### ISSUE TITLE
Latest update throwing an error

### ISSUE THREAD

**Issue by Jogib** [WooMinecraft/woominecraft-wp#18]
With the latest WP update you are met with the following error, after payment of a product:
{"success":false,"data":{"msg":"Keys do not match, compare keys in WordPress to your config.yml"}}

I have double checked that the keys are the same.

The link in my browser shows:
http://domain.com/check-out/order-received/467/?key=wc_order_12cd345a67fa8 (not my real key)
It only shows 13 digits of the key. the full length of a key is 32?

**Comment by JayWood** [comment]
@Jogib AHHH Okay, WooCommerce uses the same 'key' as WMC... great... expect a fix today.

**Comment by Jogib** [comment]
Thanks :)
