### ISSUE TITLE
Not receiving items

### ISSUE THREAD

**Issue by TheSodaPopPanda** [WooMinecraft/woominecraft-wp#22]
Hi again, sorry to bug you, this is probably just me missing something if some very sorry!
I have set everything in the Minecraft plugin config,
and WooCommerce. how every when I go to test it ( give %s apple 64 ) I never get the items :(

**Comment by TheSodaPopPanda** [comment]
also, I'm getting this in console (server console)


> Server] WARN [WooMinecraft] A JSONObject text must begin with '{' at 1 [character 2 line 1]

**Comment by JayWood** [comment]
That's why you're not getting it, set debug to true in the config.

**Comment by TheSodaPopPanda** [comment]
I have debug set to true and I am still only getting this line 

> WARN [WooMinecraft] A JSONObject text must begin with '{' at 1 [character 2 line 1]

NOTE: I have restarted

**Comment by TheSodaPopPanda** [comment]
Hello...?

**Comment by JayWood** [comment]
@TheSodaPopPanda This was the problem https://github.com/WooMinecraft/woominecraft-wp/commit/dd5330a23b78cfad4e671bf759359cbd70749f6f

Testing on my dev seems that it works as expected.

**Comment by JayWood** [comment]
Closing, assumed fix, please let me know if it's not.
