### ISSUE TITLE
Multi support not working 1.10.2   [WooMinecraft] rpcreative.xyz: UnknownHostException

### ISSUE THREAD

**Issue by LPGamersRob** [WooMinecraft/woominecraft-wp#23]
Hi there.

As of our previous messages about multi server support throwing me an error i have given the new updated plugin a run and this is still giving me the same error. https://gyazo.com/893aa881c49248a66eb9ee03c6ff7fe9
here you can see that the plugin is enables and running but lower down when the plugin runs it's command of /woo check it then fails again. 

i thought that it may be a problem with the idea of the plugins i have been using so got rid and restarted a server with the bungee setup i have and it still did the same thing.

is there possibly a problem with porting from the server (i run my whole server on a VPS). if so what port could it possibly be i can then try force opening this port and see what i get from that.

a few little fact about my server (hoping this will help more)
Versions running:
1. Running bungee 1.10 version latest build.
2. Running spigot 1.10.2 latest build (i check daily and update if needed).
3. running on a vps with Debian 7.8.0 Amd64 as the OS.
4. using java 8 as of last update.

**Comment by JayWood** [comment]
Changed the title to reflect the error. I'll continue to look into this, sorry for the issues 😞

**Comment by LPGamersRob** [comment]
Thank you and dont worrie about it, i know there is bug in thing and that it may take a fair while to over come but i will be waiting patiently for this as i think that this better than using a premade / buycraft crap.

**Comment by JayWood** [comment]
Yea, that's the sole reason i made it, was tired of BuyCraft. I did some preliminary tests today with a few different approaches, to no avail.

So, what I'm going to try next is hit your server with some request on a custom made Java plugin and see what I get back.

Unfortunately the work week is starting come Monday, so I'll be doing this during free time obviously. Thanks again for your understanding.

**Comment by LPGamersRob** [comment]
that is okay, just so you knwo i am also getting my host provider to looking to a few thing because all of my plugins have now started giving me problems.

none of them can look for updates, and my vote system seems to not pick up any connection.

ill let you know how this go's.

**Comment by JayWood** [comment]
Looking at the error, i would ask your hosting provider if he's using IPv6 vs ipv4 as well, just a thought. Good luck!

**Comment by LPGamersRob** [comment]
this i what i got in response but am still talking to support at this time about it all.

https://gyazo.com/807b014e247a39e0dcd9b4ac455f485d

**Comment by LPGamersRob** [comment]
Hi, Just so you know i have got it all working, i have had my hosting company do alot of testing on my server and it turns out that for some odd reason there was no outbound connection and i tihnk that everything is working and that the plugin can now do it's requests.

**Comment by JayWood** [comment]
Would love you to confirm that, also, did they give you specifics on what the issue was? Like a server config etc?

**Comment by LPGamersRob** [comment]
This is the reply i get from woo check https://gyazo.com/887e7be170a59294cf4372067fece1e3

here is a shot of the shop giving 64 diamonds aswell
(shop setup https://gyazo.com/6512dcc334c1bfc8af7fefbbae0e01b5 )
( items given to player https://gyazo.com/bf2f3ca70c439f75bee544ccb668d589 )

and the problem turned out to be an outbound connection problem on the VPS. i got asked to run a few pings and to check the server config and got told there was a problem there so it got changed and now works.

when this command has run on one server though it seems not to give the player anything on the other when doing woo check?  is there a way of making it so that player are given them but it is held untill they are active on that server ?

Thanks Robert

**Comment by JayWood** [comment]
When the command is ran on one server, it's not ran in a synchronous fashion on other servers, ie. running it on server A will not also run it on server B.

Commands are keyed by server, so each server has it's own key, and set of commands it can pull. You have to also run the command on server B ( or let the timer hit ) for the command to run.

If the user is not online, then it will not attempt to give them the item.

**Comment by LPGamersRob** [comment]
oh okay that makes a lot more sense. it just seemed not to work at the beginning but i have been playing for a few more hours and it seemed to give me the items that it should. 

but then when i was on a server i have not done any work on in a few days and i did /woo check it give me 11 times the item amount. but i will keep an eye on things to see if that was not just a glitch i have done.

**Comment by LPGamersRob** [comment]
so i have not ran into a small problem.

when i have done a test item free diamonds, i get them on all server now but i seem to get given this every day and it gives me more everytime im now at a point where my inventory gets filled each time, i dont seem to get any errors in my console it just happens now,

Thanks Robert.

**Comment by JayWood** [comment]
Closing this for now, so much has happened since, feel free to re-open.
