### ISSUE TITLE
Add and Remove Server buttons in settings do nothing

### ISSUE THREAD

**Issue by dordsor21** [WooMinecraft/woominecraft-wp#25]
Having added the/a server via the release version of WooMCwp, after updating to the latest dev version as the server-wp link wasn't working (making an issue right after this one), the buttons specified in the title at WooCommerce\settings\WooMinecraft Options don't do anything when pressed

**Comment by JayWood** [comment]
This is a known issue with the dev build, and was recently patched over the weekend.  If you're using the dev build get this zip - https://github.com/WooMinecraft/woominecraft-wp/archive/dev.zip

**Comment by dordsor21** [comment]
still doesn't work on that version

**Comment by dordsor21** [comment]
Fixed
