### ISSUE TITLE
Commands do not save

### ISSUE THREAD

**Issue by dordsor21** [WooMinecraft/woominecraft-wp#27]
When adding commands to be run when a player donates, they do not get saved after editing and clicking "update" on the right.

**Comment by JayWood** [comment]
general or variable, or both?

**Comment by dordsor21** [comment]
Afaik only on basic products

**Comment by rbtkooijman** [comment]
Only the last command seems to save after saving the product. 

Added commands:

![added commands](https://cloud.githubusercontent.com/assets/6112985/22968004/11682ea4-f369-11e6-9d27-3004e7c1b2f2.png)

After saving the product:

![commands after saving product](https://cloud.githubusercontent.com/assets/6112985/22968012/17d1e4b0-f369-11e6-9132-5b5240ec6827.png)


The commands are general and the product is marked basic, virtual and downloadable.

**Comment by JayWood** [comment]
@dordsor21 @rbtkooijman This should be fixed on the latest dev push - https://github.com/WooMinecraft/woominecraft-wp/archive/dev.zip
