### ISSUE TITLE
Leaving server label and/or key empty breaks options form

### ISSUE THREAD

**Issue by rbtkooijman** [WooMinecraft/woominecraft-wp#28]
WordPress version: 4.7.2 
WooMinecraft-wp version:  1.1 pr1

In an attempt to reset and change the keys for my added servers in the WooMinecraft options panel, I left both fields of the server list blank and clicked 'save changes'. Now my options menu looks like this, and clicking 'add server' does nothing:

![server list bug](https://cloud.githubusercontent.com/assets/6112985/22967214/db3118e4-f365-11e6-8eff-4d09f53b350c.png)

I searched for the setting in my database and found that the 'wm_servers' field's value now looks like this:

![server list bug database value](https://cloud.githubusercontent.com/assets/6112985/22967215/db3345a6-f365-11e6-9ac3-c4db633da9e2.png)

Emptying the record fixes the problem, but you'll have to dive into the database for that. :)

**Comment by JayWood** [comment]
@rbtkooijman Should be good with the latest dev update.
