### ISSUE TITLE
[Error- Bug] WooMinecraft Failes to run commands on request

### ISSUE THREAD

**Issue by evanmcclan** [WooMinecraft/woominecraft-wp#32]
my woo-minecraft server is running on 1.8.8 with protocol support for 1.8-1.10.2, and everything seems to connect fine... the console window says that woominecraft connected to the shop website when requesting to send orders, but then it does not run the commands on the server.

Console output;

> 09.03 16:28:21 [Server] WARN at com.plugish.woominecraft.Util.BukkitRunner.run(BukkitRunner.java:18)
09.03 16:28:21 [Server] WARN at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:207)
09.03 16:28:21 [Server] WARN at org.json.JSONArray.getString(JSONArray.java:403)
09.03 16:28:21 [Server] WARN org.json.JSONException: JSONArray[0] not a string.
09.03 16:28:21 [Server] WARN JSONArray[0] not a string.
09.03 16:28:21 [Server] INFO Command Set: [["mycmd btell §8[§7Electives§8] §6Player §f%s §6Has joined the §a§lExpert Building§6 Elective!","mycmd tellto %s §bYou are now a registered student for this class, you will receive an email whenever this class is going to happen, or you can check class times in-game with §e§l/Class§b and clicking on your class name, or by doing §c§l/NextClass"]]
09.03 16:28:21 [Server] INFO Processing command for order: 263
09.03 16:28:21 [Server] INFO Walking over orders for player.
09.03 16:28:21 [Server] INFO Checking for player: HDMrWafflez
09.03 16:28:21 [Server] WARN Player not found.
09.03 16:28:21 [Server] INFO Checking for player: noodles1598
09.03 16:28:21 [Server] INFO Player names acquired -- walking over them now.
09.03 16:28:21 [Server] INFO Content Body Snippet (128 chars): {"success":true,"data":{"Evan_McClan":{"520":["\/bc &amp;6test","bc &amp;atest"],"518":["mycmd btell \u00a78[\u00a77Electives\u0
09.03 16:28:21 [Server] INFO HTTP Response Code: 200
09.03 16:28:21 [Server] INFO Headers: [Date: Thu, 09 Mar 2017 22:28:20 GMT, Server: Apache, X-Powered-By: PHP/5.6.30, Pragma: no-cache, Expires: Wed, 11 Jan 1984 05:00:00 GMT, Cache-Control: no-cache, must-revalidate, max-age=0, Set-Cookie: PHPSESSID=bbkg85i7siljkfd0bb14vq4tc3; path=/, Set-Cookie: wordpress_google_apps_login=1d823abbfa4d407c4377b91adac61bb2; path=/; secure, Vary: Accept-Encoding,User-Agent, Keep-Alive: timeout=10, max=200, Connection: Keep-Alive, Content-Type: application/json; charset=UTF-8]
09.03 16:28:21 [Server] INFO URL Config Field: https://www.onebignation.net
09.03 16:28:21 [Server] INFO Sending Request

I dont know if there should only be one jar on the server, as i said before, we do have protocol support, so it did install woominecraft jars for every version between 1.8.8 and 1.10.

**Comment by TekkitCommando** [comment]
Multiple plugin jars are ambiguous and cause problems. You only need one jar.

**Comment by JayWood** [comment]
Multiple plugins are bad mojo, you should only use the one version that fits your MC version.

Regardless this is not the full log. There is content missing, for instance this `09.03 16:28:21 [Server] INFO Processing command for order: 263` tells me it's reading data from order 263.

One of these messages ( or more ) would have came way before the WARN that was provided. It's possible that the order that was saved may have been on the older command structure as well, of course I cannot tell without seeing your JSON feed.

**Comment by JayWood** [comment]
No response in two weeks, closing this support request.
