### ISSUE TITLE
Sponge Support

### ISSUE THREAD

**Issue by GTXSam** [WooMinecraft/woominecraft-wp#33]
Hello! We are currently using Enjin and we are looking at migrating to Wordpress and we'd like to use this plugin for our store, but our network is modded based. Is it possible to add support for Sponge servers too?

High regards
Auro

**Comment by TekkitCommando** [comment]
A complete re-write of the plugin in the Sponge API would be needed for that. @JayWood Good luck my friend haha. Sponge is getting pretty stable may be the perfect time to start supporting it. :)

**Comment by JayWood** [comment]
@Auroratic I do plan on sponge support, stay tuned!

**Comment by TekkitCommando** [comment]
@JayWood What do you think of sponges way of making plugins?

**Comment by JayWood** [comment]
@TekkitCommando I dabbled, still working on it though. Trying to balance Sponge and Forge really... I've yet to find a stable alternative to the old Cauldron for forge 10.2 servers

**Comment by JayWood** [comment]
Closing, new year new ideas.
