### ISSUE TITLE
Setting page

### ISSUE THREAD

**Issue by BirkhoffLee** [WooMinecraft/woominecraft-wp#35]
Hey there. I just got the newest WP fresh install and the latest release of the wp plugin. After activation, I could not find the setting page for this plugin.

**Comment by JayWood** [comment]
It's no longer just a single page, the settings for the plugin is now under the WooCommerce settings screen, at the very bottom of the screen.

**Comment by BirkhoffLee** [comment]
Do I need to generate the key by myself?

**Comment by JayWood** [comment]
Yes, just a random string of characters, the key generator command was removed. Think of it like a password on a per-server basis.

**Comment by BirkhoffLee** [comment]
I see. I'll open a pull request to update the documentation.
