### ISSUE TITLE
WP REST API Support

### ISSUE THREAD

**Issue by JayWood** [WooMinecraft/woominecraft-wp#37]

**Comment by TekkitCommando** [comment]
Could you please elaborate on this idea? What exactly do you mean.

**Comment by TekkitCommando** [comment]
Like a ReST API for users to use for custom solutions? Or do you want to switch over the actual app to a better ReST setup?

**Comment by JayWood** [comment]
The WordPress side of things will be moving to use the WordPress REST API instead of custom query strings. This also means the JAVA side of things can use most readily available REST client libraries instead of the current custom Apache HTTP implementation

In short, this will make endpoints available for both getting server commands, and processing orders, while still using server keys.

And no, keys won't be exposed in endpoints.

**Comment by JayWood** [comment]
Changed the title to make it less confusing.

**Comment by TekkitCommando** [comment]
Ah okay.
