### ISSUE TITLE
Progress?

### ISSUE THREAD

**Issue by downboy** [WooMinecraft/woominecraft-wp#41]
Hello,

how is this project going? I'm running some test on my network with the plugin and WP. First, I need to tell you I love it! but I have some problems with orders that are complete will not be sent to the server. When i check the ?wmc_key=<key> the commands and order number are not there. 1/5 orders will not be processed by the server. 

i hope someone can help me or can tell me if this bug is fixt in the new 2.0.0?

greetings

**Comment by JayWood** [comment]
Orders must have a `status` of complete currently. Check the orders and their status. Typically orders are set to `processing` once paid for in most scenarios, and this is not enough.

**Comment by downboy** [comment]
I had to change some of my settings, but its working now. Thanks.

I have a strange issue, can't explain it in words but I can let it show with images.
![Image of commands](https://image.prntscr.com/image/80ROQgBgRCyCr0rMdIUrCw.png)

When I place an order in my store I get this output from the server
![Image of issue](https://image.prntscr.com/image/sl9F7Z8wT3qF6-TQtdO3OA.png)

**Comment by JayWood** [comment]
@downboy Looks like this is on the return trip. The logic is like so:

1. Get data from server
2. Process commands per user
3. Add each processed command to a `processed` JSON array
4. Send the update back to the server

Sound like `3` is breaking. But I'm not sure why, so let met test with these settings and I'll get back to ya.

**Comment by downboy** [comment]
@JayWood and have you found something??

**Comment by JayWood** [comment]
Cleaning this up, if this happens after the next release let me know we'll re-visit.
