### ISSUE TITLE
Wordpress is not sending JSON

### ISSUE THREAD

**Issue by lwaite9** [WooMinecraft/woominecraft-wp#42]
I have a test item in my woocommerce side, but when attempting to "purchase" the item for $0.00, the system automatically sets the status to "processing," as expected. However, after manually setting the status to "completed," well. Pictures are likely the best way to show this.
![image](https://user-images.githubusercontent.com/5608236/28398192-031651a2-6cd4-11e7-87ce-08693038b259.png)
![28398355-dfe763dc-6cd4-11e7-8ef3-7d97f9b4faf6](https://user-images.githubusercontent.com/5608236/28398519-8a7c0aaa-6cd5-11e7-9e34-94c8de5fd041.png)
![image](https://user-images.githubusercontent.com/5608236/28398357-e7112968-6cd4-11e7-8698-b994e60d3a3c.png)
![image](https://user-images.githubusercontent.com/5608236/28398378-f977e9d4-6cd4-11e7-9f5e-b5d13998dce9.png)

I am using a key, and it is working, because my server log shows this:
`>woo check`
`[22:50:27 INFO]: [WooMinecraft] Sending Request`
`[22:50:27 INFO]: [WooMinecraft] URL Config Field: http://theshardmc.us`
`[22:50:27 INFO]: [WooMinecraft] Headers: [Date: Thu, 20 Jul 2017 02:50:26 GMT, Server: Apache, X-Powered-By: PHP/5.5.38, Connection: close, Transfer-Encoding: chunked, Content-Type: application/json; charset=UTF-8]`
`[22:50:27 INFO]: [WooMinecraft] HTTP Response Code: 200`
`[22:50:27 INFO]: [WooMinecraft] Content Body Snippet (128 chars): {"success":true,"data":[]}`
`[22:50:27 INFO]: [WooMinecraft] Data check was not an instance of JSONObject, so bailing.`

So it's connecting and getting an empty response, and if I go to manually send the donation, it just says "deleted()" for the server list...

I'm not really sure what's gone wrong. Please help!

**Comment by JayWood** [comment]
Deleted means the key was changed at some point. Or you saved an empty key then added new ones. This is expected behavior, closing.
