### ISSUE TITLE
No admin panel

### ISSUE THREAD

**Issue by OutcastN3cr0** [WooMinecraft/woominecraft-wp#43]
Hello,
I have recently reinstalled your WP plugin on my wordpress site (WP version: 4.8.1) and I am wondering why how to access it if is even accessible. This is a screenshot of what is happening: http://imgur.com/a/OoOnQ , To duplicate, all you need to do is get a wordpress site and install this plugin on the latest version (and all the dependencies). I thank you for reading this (sorry if this is a bit low quality but I was in a rush)!

**Comment by JayWood** [comment]
i REALLY should update the wiki 😢 lol - it's in WooCommerce > Settings ( at the bottom )

**Comment by ksrawlot** [comment]
![capture](https://user-images.githubusercontent.com/35670389/35199692-8dd070ee-ff27-11e7-9882-fda1efdb0847.PNG)

**Comment by ksrawlot** [comment]
where

**Comment by JayWood** [comment]
According to your screenshot @ksrawlot you don't even have WooCommerce installed. This plugin is **not** a stand alone plugin, it requires WooCommerce.
