### ISSUE TITLE
Returning all requests for any key

### ISSUE THREAD

**Issue by LuizHTS** [WooMinecraft/woominecraft-wp#47]
Hello, sometimes the woominecraft is returning the requests from the X server in the Y server key.

The keys are different, and the names of the servers as well.

**Comment by JayWood** [comment]
Will look into this, apparently you're not the only one.

**Comment by LuizHTS** [comment]
Ok, thank you!

I'll wait for your response to see if the problem has been fixed.

Sorry for my bad english.

**Comment by JayWood** [comment]
@LuizHTS this should be fixed from this commit https://github.com/WooMinecraft/woominecraft-wp/commit/a53eb19ceeabee97a46ab794c0be271099118698

Note the wordpress plugin code is now in the `/src` directory, more details later, but for now if you download at that commit this should fix your problems.

**Comment by LuizHTS** [comment]
Hello Jay, I tested it, but the requests are still returning on all keys :(

**Comment by JayWood** [comment]
Make sure you clear any and all caching, especially cloudflare

**Comment by LuizHTS** [comment]
I did this, is it because I'm using version 1.1?

**Comment by JayWood** [comment]
The new version should show 1.2

**Comment by LuizHTS** [comment]
Thank you JayWood, i updated the plugin for version 1.2 and it is working perfectly.
