### ISSUE TITLE
PHP/WordPress Plugin Question

### ISSUE THREAD

**Issue by TekkitCommando** [WooMinecraft/woominecraft-wp#5]
@JayWood, Ok so I was picking programming classes today and I thought it would be cool to help with the PHP side of things for WooMinecraft and It would be cool to know a language more geared to web development as well so I had 5 classes to enroll in and I enrolled in PHP Development as one of them. I was wondering if there were any resources you could point me to that shows me how the WordPress API works, or is my best bet just reading the documentation on the WordPress codex.

**Comment by JayWood** [comment]
This should get you going - https://codex.wordpress.org/Writing_a_Plugin

Above all, once you start to understand WordPress and how it works, the Codex will be your best bet. The answer to most of your questions @TekkitCommando when it comes to WordPress is - "There's a function for that".

**Comment by TekkitCommando** [comment]
Thanks :P
