### ISSUE TITLE
Where can a player enter it's playername when purchasing?

### ISSUE THREAD

**Issue by Peda1996** [WooMinecraft/woominecraft-wp#51]
Hello,

I just downloaded your Plugin. My only problem is, where can buyers add there Minecraft username?

Greetings from Austria

**Comment by Peda1996** [comment]
Found it, thanks anyways 🗡 

Found another very small bug, the github link in the plugin description isn't working.

**Comment by HoLiSchit** [comment]
I already answered by email, so it might appear twice:
they can enter their playername on the checkout page, above their real name on the form

**Comment by Peda1996** [comment]
Thanks for the fast answer.

How to automatically change the state from inprogress to finished?

Thanks for the help

**Comment by HoLiSchit** [comment]
Theres an Plugin for that: https://de.wordpress.org/plugins/autocomplete-woocommerce-orders/
in **woocomerence** settings set the autocomplete orders tab "Paid orders of virtual products only" and save.

Glad to hel :)

**Comment by Peda1996** [comment]
You're a real live savior, thanks for your support :)
