### ISSUE TITLE
Hook into the permissions ex database

### ISSUE THREAD

**Issue by Peda1996** [WooMinecraft/woominecraft-wp#52]
It would be quite nice, if woominecraft can hook into the database, where permissions ex is, and therefore check what rank a player has, and if the player already has a certain permisions.

So therefore Buy Upgrades would be possible. (like Rank upgrades)

**Comment by ethsmith** [comment]
Vault can be used for that so there is support for almost every permission system.

**Comment by JayWood** [comment]
This has been asked before, the solution is still available for those servers who 'pay for a rank' - https://wordpress.org/plugins/woocommerce-product-dependencies/

> Restrict access to any WooCommerce product, depending on the ownership and/or purchase of other, required products.

Using product dependencies will force users to have ownership of a `previous rank` per-se before they can purchase the next one above.

**Comment by JayWood** [comment]
@Peda1996 this is what you're looking for correct?

**Comment by Peda1996** [comment]
Yea, is this also possible without the registration of the use (therefore depending on the username) r?

**Comment by Peda1996** [comment]
I am now using the plugin without user registration, therefore using this plugin is sadly no option for me. Also I had a look at the database. Is it possible that the user uuid isn't saved? (this would be mandatory, if dependencys based on minecraft names would be added)

**Comment by JayWood** [comment]
UUID's are not stored in the DB for this version, only plain-text names that is entered during checkout. The data is stored against the order ( I forget the key but it's in the repo )

**Comment by JayWood** [comment]
Closing this, it's a new year, feel free to reopen if needed.
