### ISSUE TITLE
time based items

### ISSUE THREAD

**Issue by mmuziek** [WooMinecraft/woominecraft-wp#6]
Hi there.
my suggestion is subscription items. or variable time stamps

soo a player chooses 30 days from a variable option or choose a month or buys a month item.
they currently get their rank ingame but its never removed automaticly

are there plans to implent this or not? or are there other ways to do this free or for a small fee?

this is my suggestion thanks for reading :D

**Comment by JayWood** [comment]
See response here - https://github.com/WooMinecraft/WooMinecraft/issues/62
