### ISSUE TITLE
Purchase isn't forwarded to the server!

### ISSUE THREAD

**Issue by jannis2200** [WooMinecraft/woominecraft-wp#65]
Hi,
I have WooMinecraft installed on my Wordpress Installation and on my Minecraft server. The plugin works and doesn't display any errors, but the URL, where the orders are displayed in JSON (the endpoint for the plugin) does always (if you buy something, too) show nothing. --> The orders aren't executed in Minecraft.
How can I fix this?
I couldn't find any errors in Wordpress, too.

Best regards,
Jannis2200

PS: Is there a Bungeecord-Version for the Minecraft plugin?

**Comment by mmuziek** [comment]
Set the order as completed some gatewars keep it at processing

**Comment by jannis2200** [comment]
Thx, this was the Problem :)
