### ISSUE TITLE
Reinstalling issue Wordpress

### ISSUE THREAD

**Issue by pjindras** [WooMinecraft/woominecraft-wp#67]
Hi, i moved my website to diffend hosting with diffend domain and diffend ssl and after that, the plugin is not working good. So i decided to reinstall it BUT, when i simply deactivate it and remove it, the data stays in the db and after instalation everything is like it was before, SO 

How to reinstall it completely?

Thanks a lot!

I reistalled woocommerce too, but there is only one line to add to wp-config and woocommerce is uninstalled good, the issue must be in your plugin.

**Comment by JayWood** [comment]
I think at this time you would need to delete the meta settings complete. Will close this in favor of #75
