### ISSUE TITLE
Error on HTTP request

### ISSUE THREAD

**Issue by ThugJarno** [WooMinecraft/woominecraft-wp#69]
22.10 00:01:51 [Server] SEVERE java.io.IOException: Server returned HTTP response code: 403 for URL: ******
22.10 00:01:51 [Server] SEVERE at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
22.10 00:01:51 [Server] SEVERE at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92)
22.10 00:01:51 [Server] SEVERE at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1490)
22.10 00:01:51 [Server] SEVERE at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1488)
22.10 00:01:51 [Server] SEVERE at java.security.AccessController.doPrivileged(Native Method)
22.10 00:01:51 [Server] SEVERE at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784)
22.10 00:01:51 [Server] SEVERE at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1487)
22.10 00:01:51 [Server] SEVERE at java.net.URL.openStream(URL.java:1067)

**Comment by JayWood** [comment]
https://en.wikipedia.org/wiki/HTTP_403

Means access from your game server to the WP-JSON endpoint specifically /wp-json/wmc/v1/ is forbidden - confirm with your host the issue. Can't be of help from this side.
