### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by mmuziek** [WooMinecraft/woominecraft-wp#7]
Hi there.
i found out that it doesnt create the database at all!

just wanna let you know that it is not making the table when i install the plugin.
soo to be short everything failes at start because it doesnt have a database.
after that it still doesnt create any json on the website thats why the plugin cannot read it.
i hope you find a solution.

greetings from mmuziek

**Comment by JayWood** [comment]
Thanks @mmuziek I'll look into that.

**Comment by JayWood** [comment]
@mmuziek Confirmed, last commit fixed it.
