### ISSUE TITLE
Adding support for subscriptions

### ISSUE THREAD

**Issue by martineriksson** [WooMinecraft/woominecraft-wp#74]
I would very much like to use WooMinecraft but I need to have subscriptions. I might be willing to add this feature myself but I thought I should ask a few questions first.

Is this something that has been considered and perhaps even worked on?

Any hints for how to go about implementing it?

**Comment by JayWood** [comment]
I have received a few requests for this. At it's core the plugin it basically stores a list of commands to be ran for a specific order ( WordPress Post ID ) - which is stored as post meta. When an order is delivered a meta key of `_wmc_delivered_<key>` is added to that order which then ensures it isn't pending delivery. That happens here - https://github.com/WooMinecraft/woominecraft-wp/blob/9f67c873a9fb1dc9727c481b1749177f5d506402/includes/rest-api.php#L134

There are many ways to handle subscriptions, the reason it's not been done yet is there are so many edge cases for myself.

**Comment by martineriksson** [comment]
Thank you very much for the reply!

**Comment by JayWood** [comment]
No problem, glad to help.
