### ISSUE TITLE
Username not registered at Moajng cannot do orders

### ISSUE THREAD

**Issue by marcopaggioro** [WooMinecraft/woominecraft-wp#77]
Hi,
player with cracked usernames, not registered at mojang so "free" names, cannot do orders.
Error: We cannot retrieve your account from the Mojang API. Try again later, or contact an administrator.
We use WooMinecraft-WP 1.4.0

**Comment by JayWood** [comment]
I do not support 'cracked' or 'free' usernames. I paid for the game, they should too.
