### ISSUE TITLE
We cannot retrieve your account from the Mojang API. Try again later, or contact an administrator.

### ISSUE THREAD

**Issue by BuildingDave** [WooMinecraft/woominecraft-wp#79]
Hi @JayWood 

I get this Message in WooCommerce Checkout:

We cannot retrieve your account from the Mojang API. Try again later, or contact an administrator.

This has been the case since today.

I already installed pre 1.4. Unfortunately without success.

do you have a solution?

**Comment by mrtimelord** [comment]
We're also experiencing the same issue. Tried it multiple times from different parts of the world with the same result.

**Comment by JayWood** [comment]
Microsoft must have dropped support for the mojang API - the latest pre-release should solve that - https://github.com/WooMinecraft/woominecraft-wp/releases/tag/1.4.0-pre

**Comment by BuildingDave** [comment]
@JayWood i have install this Version  :-/

**Comment by BuildingDave** [comment]
after it stopped working i updated everything in wordpress as well.
Unfortunately, it didn't work after that either.

I installed 1.4.0-pre manually and removed 1.3.0.
unfortunately no success.
