### ISSUE TITLE
We cannot retrieve your account from the Mojang API. Try again later, or contact an administrator.

### ISSUE THREAD

**Issue by NicolasXD5** [WooMinecraft/woominecraft-wp#84]
who does not use original minecraft, this message appears. What do I do?

**Comment by troke12** [comment]
literally in README there are FAQ that not supporting offline-mode users, so maybe that's why

**Comment by pokeboll0jakub** [comment]
I have the same, but I have the original one and it doesn't work for me

**Comment by JayWood** [comment]
Removing this ticket as it's related to an offline server. Latest tests proved okay.
