### ISSUE TITLE
Item received multiple times

### ISSUE THREAD

**Issue by ehetteNandaYo** [WooMinecraft/woominecraft-wp#85]
For some reason if I buy something and i dont remove the item from the list it never stops from deliverying it.

stays like this for a long time and if I do /woo check it just keeps sending it
![image](https://user-images.githubusercontent.com/62739770/120447814-f6cb7780-c358-11eb-8f78-740a0b3cefa9.png)

any idea how to debug this ??

**Comment by 3Nator** [comment]
in woocomerece  order status must be completed maybe thats ur problem

**Comment by csuoffice40711137** [comment]
Install the WordPress plug-in to solve your problem!
https://wordpress.org/plugins/autocomplete-woocommerce-orders/

**Comment by JayWood** [comment]
I believe the issue here is that when sending the data back from the website I'm not checking it properly. Will verify in the 2.0 release.

**Comment by JayWood** [comment]
This directly relates to the result of sendProcessedOrders - wondering if I should attempt to 'process' the orders first and then give the items instead of give then process.

**Comment by JayWood** [comment]
Closing this, no feedback in quite some time.
