### ISSUE TITLE
Why not use RCON?

### ISSUE THREAD

**Issue by yesBad** [WooMinecraft/woominecraft-wp#97]
Hey, I'm just wondering why doesn't this plugin simply use RCON. That would remove the need for a plugin.

**Comment by JayWood** [comment]
Because I like APIs and REST and all that jazz.

**Comment by yesBad** [comment]
Well I guess that answers it 😅

**Comment by JayWood** [comment]
Rcon is a valid thing to use though. I guess the real answer here is when I originally created the plugin I was more interested in utilizing java and educating myself on Java - which I continue to do. I have some code that works with RCON for this purpose though. I just don't see me integrating it into this, maybe as an addon/alternative.

**Comment by yesBad** [comment]
I forgot to respond to this, and this would be wonderful to be fair. It'd work for modded too :o
