### ISSUE TITLE
bug wp - not enabled plugin

### ISSUE THREAD

**Issue by TOWUK** [WooMinecraft/woominecraft-wp#98]
wtf? latest wp and plugin, where menu?
![image](https://user-images.githubusercontent.com/28830162/153901298-be3247f7-a57c-4652-8e92-7dd3b19090b4.png)

**Comment by JayWood** [comment]
Requirements are listed on the Spigot plugin listing - https://www.spigotmc.org/resources/woominecraft-donation-plugin.25517/

Looks like you're missing something important. Maybe check the link above.
![image](https://user-images.githubusercontent.com/2303074/153926807-4812b3ae-8f89-4964-8ae8-cf497c9ee30f.png)
